import MainNav from '@/components/MainNav'
import { useEffect, useState } from 'react'
import { AppProps } from 'next/app'
import { SessionContextProvider } from '@supabase/auth-helpers-react'
import { createBrowserSupabaseClient } from '@supabase/auth-helpers-nextjs'
import { MyUserContextProvider } from '@/utils/useUser'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    const [supabaseClient] = useState(() => createBrowserSupabaseClient<Database>())
    <html lang='en'>
      <body className=''>
        <SessionContextProvider supabaseClient={supabaseClient}>
          <MyUserContextProvider>
            <MainNav />
            {children}
          </MyUserContextProvider>
        </SessionContextProvider>
      </body>
    </html>
  )
}
