import Image from 'next/image'
import Layout from '@/components/Layout'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function Home() {
  return (
    <main className='flex flex-col items-center justify-between min-h-screen p-24'>
      <Layout>
        <div className='blotch'></div>
      </Layout>
    </main>
  )
}
